# Based on: https://github.com/microsoft/psscriptanalyzer-action/blob/main/action.yml
name: PowerShell Analysis
description: Invoke PSScriptAnalyzer and produce SARIF report

inputs:
  analysis:
    description: 'Hashmap with arguments for Invoke-ScriptAnalyzer'
    default: '@{}'
  conversion:
    description: 'Hashmap with arguments for ConvertTo-Sarif'
    default: '@{}'
  serialization:
    description: 'Hashmap with arguments for ConvertTo-Json'
    default: '@{}'
  output-path:
    description: 'Specifies the path for the SARIF file'
    default: 'results.sarif'

runs:
  using: composite
  steps:
    - name: Run PSScriptAnalyzer and ConvertToSARIF
      shell: pwsh
      env:
        analysis: ${{ inputs.analysis }}
        conversion: ${{ inputs.conversion }}
        serialization: ${{ inputs.serialization }}
      run: |
        . './.github/actions/analyze-powershell/sarif-utils.ps1'

        Invoke-ScriptAnalyzerAction -OutputPath '${{ inputs.output-path }}'