//<auto-generated/>
#nullable enable
#pragma warning disable

#if !NETSTANDARD2_1_OR_GREATER && !NETCOREAPP2_1_OR_GREATER && !NET5_0_OR_GREATER

using System.Runtime.CompilerServices;

namespace System;

internal static partial class LocalAppContextSwitches
{
    private static int s_useNonRandomizedHashSeed;

    public static bool UseNonRandomizedHashSeed
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => GetCachedSwitchValue("Switch.System.Data.UseNonRandomizedHashSeed", ref s_useNonRandomizedHashSeed);
    }
}

#endif