//<auto-generated/>
#nullable enable
#pragma warning disable

#if !NETSTANDARD2_1_OR_GREATER && !NETCOREAPP2_0_OR_GREATER && !NET5_0_OR_GREATER

using System.ComponentModel;

namespace System.Collections.Generic;

internal static class KeyValuePairExts
{
    [EditorBrowsable(EditorBrowsableState.Never)]
    public static void Deconstruct<TKey, TValue>(this KeyValuePair<TKey, TValue> @this, out TKey key, out TValue value)
    {
        key = @this.Key;
        value = @this.Value;
    }
}

#endif