name: Publish NuGet package
description: Publish a NuGet package on a NuGet server

inputs:
  artifact-name:
    description: 'Name of the artifact to download.'
    required: true
  artifact-path:
    description: 'Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE'
    required: true
  source:
    description: 'The NuGet server URL.'
    required: true
  api-key:
    description: 'The API key for the NuGet server.'
    required: true

runs:
  using: composite
  steps:
    - name: Download packages
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}

    - name: Publish to NuGet
      shell: pwsh
      run: >
        dotnet nuget push
        (Join-Path "${{ inputs.artifact-path }}" "*.nupkg")
        --source ${{ inputs.source }}
        --api-key ${{ inputs.api-key }}
        ${{ env.base_nuget_args}}