name: Publish NuGet package
description: Publish a NuGet package on a NuGet server

inputs:
  path:
    description: 'Path to the directory containing .nupkg and .snupkg files'
    type: string
    required: true
    default: Artifacts/
  api-key:
    description: 'The API key for the server'
    type: string
    required: true
  source:
    description: 'Package source URL to use'
    type: string
    required: false
    default: https://api.nuget.org/v3/index.json
  symbol-api-key:
    description: 'The API key for the symbol server. If not specified, api-key is used.'
    type: string
    required: false
  symbol-source:
    description: 'Package symbol source URL to use. If not specified, source is used.'
    type: string
    required: false
  no-symbols:
    description: 'Do not push symbols, even if they exist.'
    type: boolean
    required: false
    default: false
  timeout:
    description: 'Timeout for pushing to a server in seconds'
    type: number
    required: false
    default: 300

runs:
  using: composite
  steps:
    - name: Publish NuGet packages
      shell: pwsh
      run: |
        dotnet @(
          'nuget', 'push'
          (Join-Path "${{ inputs.path }}" "*.nupkg")
          '--skip-duplicate'
          '--force-english-output'
          '--api-key', "${{ inputs.api-key }}"
          '--source', "${{ inputs.source }}"
          '--timeout', "${{ inputs.timeout }}"
        ) + (
          ${{ inputs.no-symbols }} ? @(
            '--no-symbols'
          ) : @(
            '--symbol-api-key', "${{ inputs.symbol-api-key || inputs.api-key }}"
            '--symbol-source', "${{ inputs.symbol-source || inputs.source }}"
          )
        )