name: Restore NuGet packages
description: Restore NuGet packages and tools with cache

runs:
  using: composite
  steps:
    - name: Cache NuGet packages
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          ~/.nuget/packages
        key: >-
          ${{ runner.os }}-nuget-${{
            hashFiles(
              '**/NuGet.config',
              '**/Directory.Packages.props',
              '**/dotnet-tools.json',
              '**/packages.lock.json'
            )
          }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore NuGet packages
      #if: steps.cache.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        dotnet restore
        dotnet tool restore